// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njwbpdtkhosvnjitydct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qd2JwZHRraG9zdm5qaXR5ZGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTIwOTksImV4cCI6MjA2NjE4ODA5OX0.plUZ6Klj__LsIeAUyRAOnL6DDxx7rGP-rl1WEpVw7Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);